server:
  port: 8900
  servlet:
    context-path: /

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/user/**
        - id: like-service
          uri: lb://like-service
          predicates:
            - Path=/v1/like/**
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/v1/post/**
        - id: feed-service
          uri: lb://feed-service
          predicates:
            - Path=/v1/feed/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v1/notification/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost