server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bpmzw3mnf1uhkgom6cpd-mysql.services.clever-cloud.com:3306/bpmzw3mnf1uhkgom6cpd
    username: uptksjqyruupwrco
    password: hnU79Jw6X5rzdKOZHyPO
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost