server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: feed-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost

url:
  post-service: http://post-service
  user-service: http://user-service
  like-service: http://like-service