server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: like-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:C:\Workspace\h2_db\like_db\db
    username: like-service
    password: likeservicedb
  jpa:
    hibernate:
      ddl-auto: update



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost